// app/layout.js
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";
import 'bootstrap/dist/css/bootstrap-utilities.min.css';
import '@/assets/css/spacing.css';
import '@/assets/css/style.css'; // Ensure this is loaded after Bootstrap CSS
import '@/assets/css/responsive.css';
import '@/assets/css/header.css';
import Preloader from "@/components/ui/preloader";
import Header from "@/components/sections/header";
import CallToAction from "@/components/sections/callToAction";
import Footer from "@/components/sections/footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Preloader/>
        <Header/>
        {children}
        <CallToAction/>
        <Footer/>
        </body>
        </html>
    );
}